CREATE TABLE [dbo].[Potluck]
(
	[Id] INT IDENTITY (1,1) NOT NULL,
	[Date] DATE NOT NULL,
	[Time] NVARCHAR (100) NOT NULL,
	[Host] INT,
	[Cost] DECIMAL (15,2),
	CONSTRAINT PK_POT PRIMARY KEY (Id),
	CONSTRAINT FK_HOST FOREIGN KEY (Host) REFERENCES Member (Id)
	
)
