//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotluckWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potluck
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> Host { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
